//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
